variable "aws_profile" {
  description = "The name of the shared credentials profile to use"
  type        = string
}

variable "aws_region" {
  description = "The AWS region to operate in"
  type        = string
}

variable "googleapis_secret_key" {
  description = "Secret Key for remote Google Cloud Storage"
  type        = string
}

variable "googleapis_access_key" {
  description = "Access Key for remote Google Cloud Storage"
  type        = string
}

variable "datasync_activation_key" {
  description = "The activation key generated by the datasync agent"
  type        = string
}
